spring:
  datasource:
    url: jdbc:tc:mysql:8.0.34:///second_hand
    username: root
    password: root
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
