  spring:
    profiles:
      active: prod
      include:
        - auth
        - auth2
        - aws
    jpa:
      properties:
        hibernate:
          jdbc:
          default_batch_fetch_size: 1000
      open-in-view: true


